export const ADD_DEPARTMENT_GET_REQUEST = 'ADD_DEPARTMENT_GET_REQUEST';
export const ADD_DEPARTMENT_GET_SUCCESS = 'ADD_DEPARTMENT_GET_SUCCESS';
export const ADD_DEPARTMENT_GET_FAIL = 'ADD_DEPARTMENT_GET_FAIL';
